name: talkzy_beta1
description: Pulse - A modern messaging app with friend requests and real-time chat.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  uuid: ^4.5.1
  intl: ^0.19.0
  http: ^1.5.0
  rxdart: ^0.28.0

  # Firebase & Authentication
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.0.2

  # Database & Real-time
  supabase_flutter: ^2.3.3
  cloud_firestore: ^5.4.4

  # Storage & Local Data
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # Device & Platform
  permission_handler: ^11.3.0
  flutter_contacts: ^1.1.7
  url_launcher: ^6.2.5

  # UI Components & Media
  cached_network_image: ^3.3.1
  emoji_picker_flutter: ^2.1.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/contacts.json
