name: new_task_manage
description: A Flutter dashboard app for managing tasks efficiently.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  url_launcher_platform_interface: ^2.3.2
  supabase_flutter: ^2.3.3
  supabase: ^2.0.7
  permission_handler: ^11.3.0
  flutter_contacts: ^1.1.7
  intl: ^0.19.0
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/contacts.json