// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdkY-iG0_q13GARyozmcPPfbcsDSIKmgI',
    appId: '1:808979465867:web:6bfcaf135c8457c691b68e',
    messagingSenderId: '808979465867',
    projectId: 'pulse-8033f',
    authDomain: 'pulse-8033f.firebaseapp.com',
    storageBucket: 'pulse-8033f.firebasestorage.app',
    measurementId: 'G-G6D46Z9510',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmVHgtw9tJrrkpOzfXQ5Zi7E7eePIiK0',
    appId: '1:808979465867:android:c07253cebaab5e4f91b68e',
    messagingSenderId: '808979465867',
    projectId: 'pulse-8033f',
    storageBucket: 'pulse-8033f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOzGdcXsEJXEH666SVgD-kKv7kyK8gF8',
    appId: '1:808979465867:ios:55e6caef184198ca91b68e',
    messagingSenderId: '808979465867',
    projectId: 'pulse-8033f',
    storageBucket: 'pulse-8033f.firebasestorage.app',
    iosBundleId: 'com.example.pulseMain',
  );
}
